#ifndef RENT_A_CAR_CONSTANTS_H
#define RENT_A_CAR_CONSTANTS_H

#define MAX_CUSTOMERS 1000
#define MAX_VEHICLES 300
#define MAX_OFFICES 7
#define MAX_CONTRACTS 1000
#define START_YEAR 2020
#define EPSILON 1e-6

#endif//RENT_A_CAR_CONSTANTS_H
